Issue #9 - decision tree populated
Aemilivs/2104-SC-BL-ICA-2 pull request #16
Opened 2022-01-20 16:56 UTC by h0nz1n

- decision tree expanded and populated
- **process-node** function (in chatbot.clj) changed from using "if" statement to a switch case, so answers can be broadened to at least couple colors and yes/no
- coding syntax changed to adhere more to lisp style

Resolves #9

2022-01-20 17:11 UTC, Aemilivs requested changes
I don't think that we need any changes in the application logic in this ticket.
Could you please revert them and try to introduce them as a separated issue?
Also, let's please stick to the existing formatting for the consistency 🙏

2022-01-20 17:11 UTC, Aemilivs commented on src/chatbot/chatbot.clj
> +        "black" (node "black")
Wth?

2022-01-21 12:57 UTC, h0nz1n commented
I have reverted all of the changes made to the program's logic and syntax and updated the decision tree to be only positive / negative answer based.

2022-01-21 16:48 UTC, Aemilivs approved these changes

2022-01-21 16:48 UTC, merged